#! /usr/bin/env python
# -*- coding: utf-8 -*-

# 25.January.2014 Liz Brooks
# script to populate the database with Datasource and Sensor information 
# from Nortek Weather Station and Aquadopp Profiler Thompson Island.

import populate
debug = True


if __name__ == '__main__':
    if debug: print "Starting Nortek setup script..."

    # create Nortek DataSource ------------------------------
    if debug: print "Creating Datasource..."
    mysource = populate.add_datasource( datasource_id = "Nortek Station Thompson Island",
                               owner = "Nortek",
                               latitude=42.3192,
                               longitude=-71.0104,
                               access_info="stationNo=6016 stationID=e22a07ba note .xls file is html",
                               symbol="NOR"
                           )

    # create Sensors from this datasource ---------------------------------
    if debug: print "Creating Sensors..."
    s1 = populate.add_sensor( sensor_id = "nor_Wind_speed_avg",
                     source = mysource,
                     short_name="Wind Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "meteorological",
                     line_color = populate.hex_color('dark_blue'),
                 )
    s2 = populate.add_sensor( sensor_id = "nor_Wind_speed_max",
                     source = mysource,
                     short_name="Gust Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "meteorological",
                     line_color = populate.hex_color('blue'),
                 )
    s3 = populate.add_sensor( sensor_id = "nor_Wind_direction",
                     source = mysource,
                     short_name="Wind Direction",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "meteorological",
                     line_color = populate.hex_color('black'),
                 )
    s4 = populate.add_sensor( sensor_id = "nor_Temperature",
                     source = mysource,
                     short_name="Air Temperature",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees Celsius",
                     units_short = "°C",
                     is_headliner = True,
                     kind = "meteorological",
                     line_color = populate.hex_color('red'),
                 )
    s5 = populate.add_sensor( sensor_id = "nor_Humidity",
                     source = mysource,
                     short_name="Relative Humidity",
                     data_type = "float",
                     is_number = True,
                     units_long = "percent",
                     units_short = "%",
                     kind = "meteorological",
                     line_color = populate.hex_color('light_green'),
                 )
    s6 = populate.add_sensor( sensor_id = "nor_Pressure",
                     source = mysource,
                     short_name="Air Pressure",
                     data_type = "float",
                     is_number = True,
                     units_long = "hectopascals",
                     units_short = "hPa",
                     kind = "meteorological",
                     line_color = populate.hex_color('gray'),
                 )
    s7 = populate.add_sensor( sensor_id = "nor_Rain",
                     source = mysource,
                     short_name="Precipitation Rate",
                     data_type = "float",
                     is_number = True,
                     units_long = "millimeters per hour",
                     units_short = 'mm/h',
                     kind = "meteorological",
                     line_color = populate.hex_color('cyan'),
                 )
    s9 = populate.add_sensor( sensor_id = "nor_Cell_Temperature",
                     source = mysource,
                     short_name="Water Temperature",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees Celsius",
                     units_short = "°C",
                     kind = "hydrological",
                     line_color = populate.hex_color('purple'),
                 )
    s10 = populate.add_sensor( sensor_id = "nor_Cell_Tilt",
                     source = mysource,
                     short_name="Cell Tilt",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "hydrological",
                     line_color = populate.hex_color('pink'),
                 )
    s11 = populate.add_sensor( sensor_id = "nor_Cell1_Speed",
                     source = mysource,
                     short_name="Cell1 Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "hydrological",
                     line_color = populate.hex_color('dark_blue'),
                 )
    s12 = populate.add_sensor( sensor_id = "nor_Cell1_Direction",
                     source = mysource,
                     short_name="Cell1 Direction",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "hydrological",
                     line_color = populate.hex_color('black'),
                 )
    s13 = populate.add_sensor( sensor_id = "nor_Cell1_Amplitude",
                     source = mysource,
                     short_name="Cell1 Amplitude",
                     data_type = "float",
                     is_number = True,
                     units_long = "pounds",
                     units_short = "#",
                     kind = "hydrological",
                     line_color = populate.hex_color('brown'),
                 )
    s14 = populate.add_sensor( sensor_id = "nor_Cell2_Speed",
                     source = mysource,
                     short_name="Cell2 Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "hydrological",
                     line_color = populate.hex_color('dark_blue'),
                 )
    s15 = populate.add_sensor( sensor_id = "nor_Cell2_Direction",
                     source = mysource,
                     short_name="Cell2 Direction",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "hydrological",
                     line_color = populate.hex_color('black'),
                 )
    s16 = populate.add_sensor( sensor_id = "nor_Cell2_Amplitude",
                     source = mysource,
                     short_name="Cell2 Amplitude",
                     data_type = "float",
                     is_number = True,
                     units_long = "pounds",
                     units_short = "#",
                     kind = "hydrological",
                     line_color = populate.hex_color('brown'),
                 )
    s17 = populate.add_sensor( sensor_id = "nor_Cell3_Speed",
                     source = mysource,
                     short_name="Cell3 Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "hydrological",
                     line_color = populate.hex_color('dark_blue'),
                 )
    s18 = populate.add_sensor( sensor_id = "nor_Cell3_Direction",
                     source = mysource,
                     short_name="Cell3 Direction",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "hydrological",
                     line_color = populate.hex_color('black'),
                 )
    s19 = populate.add_sensor( sensor_id = "nor_Cell3_Amplitude",
                     source = mysource,
                     short_name="Cell3 Amplitude",
                     data_type = "float",
                     is_number = True,
                     units_long = "pounds",
                     units_short = "#",
                     kind = "hydrological",
                     line_color = populate.hex_color('brown'),
                 )
    s20 = populate.add_sensor( sensor_id = "nor_Cell4_Speed",
                     source = mysource,
                     short_name="Cell4 Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "hydrological",
                     line_color = populate.hex_color('dark_blue'),
                 )
    s21 = populate.add_sensor( sensor_id = "nor_Cell4_Direction",
                     source = mysource,
                     short_name="Cell4 Direction",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "hydrological",
                     line_color = populate.hex_color('black'),
                 )
    s22 = populate.add_sensor( sensor_id = "nor_Cell4_Amplitude",
                     source = mysource,
                     short_name="Cell4 Amplitude",
                     data_type = "float",
                     is_number = True,
                     units_long = "pounds",
                     units_short = "#",
                     kind = "hydrological",
                     line_color = populate.hex_color('brown'),
                 )
    s23 = populate.add_sensor( sensor_id = "nor_Cell5_Speed",
                     source = mysource,
                     short_name="Cell5 Speed",
                     data_type = "float",
                     is_number = True,
                     units_long = "meters per second",
                     units_short = "m/s",
                     kind = "hydrological",
                     line_color = populate.hex_color('dark_blue'),
                 )
    s24 = populate.add_sensor( sensor_id = "nor_Cell5_Direction",
                     source = mysource,
                     short_name="Cell5 Direction",
                     data_type = "float",
                     is_number = True,
                     units_long = "degrees",
                     units_short = "°",
                     kind = "hydrological",
                     line_color = populate.hex_color('black'),
                 )
    s25 = populate.add_sensor( sensor_id = "nor_Cell5_Amplitude",
                     source = mysource,
                     short_name="Cell5 Amplitude",
                     data_type = "float",
                     is_number = True,
                     units_long = "pounds",
                     units_short = "#",
                     kind = "hydrological",
                     line_color = populate.hex_color('brown'),
                 )


    if debug: print "Finished Nortek setup script!"
